import type { Metadata } from "next";
import "../globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ChatLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <main className="h-full">{children}</main>;
}
